// -------------------------------------------------------------------------------
// THIS FILE IS ORIGINALLY GENERATED BY THE DESIGNER.
// YOU ARE ONLY ALLOWED TO MODIFY CODE BETWEEN '///<<< BEGIN' AND '///<<< END'.
// PLEASE MODIFY AND REGENERETE IT IN THE DESIGNER FOR CLASS/MEMBERS/METHODS, ETC.
// -------------------------------------------------------------------------------

#ifndef _BEHAVIAC_MONSTER_ID1_H_
#define _BEHAVIAC_MONSTER_ID1_H_

#include "behaviac_headers.h"

///<<< BEGIN WRITING YOUR CODE FILE_INIT

///<<< END WRITING YOUR CODE

class monster_id1 : public behaviac::Agent
///<<< BEGIN WRITING YOUR CODE monster_id1
///<<< END WRITING YOUR CODE
{
public:
	monster_id1();
	virtual ~monster_id1();

	BEHAVIAC_DECLARE_AGENTTYPE(monster_id1, behaviac::Agent)

	private: void SayHello();

///<<< BEGIN WRITING YOUR CODE CLASS_PART

///<<< END WRITING YOUR CODE
};

///<<< BEGIN WRITING YOUR CODE FILE_UNINIT

///<<< END WRITING YOUR CODE

#endif
